from PyQt6 import QtCore, QtGui, QtWidgets



class KeyboardWidget(QtWidgets.QWidget):
    def __init__(self, lang: str='en') -> None:
        super().__init__()
        self.lang = lang.lower()
        self.setObjectName("KeyboardWidget")
        self.setFixedSize(671, 241)
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 671, 241))
        self.widget.setObjectName("widget")
        self.label_yo = QtWidgets.QLabel(parent=self.widget)
        self.label_yo.setGeometry(QtCore.QRect(10, 10, 25, 40))
        self.label_yo.setMinimumSize(QtCore.QSize(25, 40))
        self.label_yo.setMaximumSize(QtCore.QSize(25, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_yo.setFont(font)
        self.label_yo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_yo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_yo.setObjectName("label_yo")
        self.label_tab = QtWidgets.QLabel(parent=self.widget)
        self.label_tab.setGeometry(QtCore.QRect(10, 55, 50, 40))
        self.label_tab.setMinimumSize(QtCore.QSize(50, 40))
        self.label_tab.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_tab.setFont(font)
        self.label_tab.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_tab.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_tab.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_tab.setObjectName("label_tab")
        self.label_caps = QtWidgets.QLabel(parent=self.widget)
        self.label_caps.setGeometry(QtCore.QRect(10, 100, 65, 40))
        self.label_caps.setMinimumSize(QtCore.QSize(65, 40))
        self.label_caps.setMaximumSize(QtCore.QSize(65, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_caps.setFont(font)
        self.label_caps.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_caps.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_caps.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_caps.setObjectName("label_caps")
        self.label_left_shift = QtWidgets.QLabel(parent=self.widget)
        self.label_left_shift.setGeometry(QtCore.QRect(10, 145, 80, 40))
        self.label_left_shift.setMinimumSize(QtCore.QSize(80, 40))
        self.label_left_shift.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_left_shift.setFont(font)
        self.label_left_shift.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_left_shift.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_left_shift.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_left_shift.setObjectName("label_left_shift")
        self.label_1 = QtWidgets.QLabel(parent=self.widget)
        self.label_1.setGeometry(QtCore.QRect(40, 10, 40, 40))
        self.label_1.setMinimumSize(QtCore.QSize(40, 40))
        self.label_1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(85, 10, 40, 40))
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(175, 10, 40, 40))
        self.label_4.setMinimumSize(QtCore.QSize(40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 40, 40))
        self.label_3.setMinimumSize(QtCore.QSize(40, 40))
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(265, 10, 40, 40))
        self.label_6.setMinimumSize(QtCore.QSize(40, 40))
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(220, 10, 40, 40))
        self.label_5.setMinimumSize(QtCore.QSize(40, 40))
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(355, 10, 40, 40))
        self.label_8.setMinimumSize(QtCore.QSize(40, 40))
        self.label_8.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(310, 10, 40, 40))
        self.label_7.setMinimumSize(QtCore.QSize(40, 40))
        self.label_7.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_0 = QtWidgets.QLabel(parent=self.widget)
        self.label_0.setGeometry(QtCore.QRect(445, 10, 40, 40))
        self.label_0.setMinimumSize(QtCore.QSize(40, 40))
        self.label_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_0.setFont(font)
        self.label_0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_0.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_0.setObjectName("label_0")
        self.label_equal = QtWidgets.QLabel(parent=self.widget)
        self.label_equal.setGeometry(QtCore.QRect(535, 10, 40, 40))
        self.label_equal.setMinimumSize(QtCore.QSize(40, 40))
        self.label_equal.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_equal.setFont(font)
        self.label_equal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_equal.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_equal.setObjectName("label_equal")
        self.label_minus = QtWidgets.QLabel(parent=self.widget)
        self.label_minus.setGeometry(QtCore.QRect(490, 10, 40, 40))
        self.label_minus.setMinimumSize(QtCore.QSize(40, 40))
        self.label_minus.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_minus.setFont(font)
        self.label_minus.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_minus.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_minus.setObjectName("label_minus")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setGeometry(QtCore.QRect(400, 10, 40, 40))
        self.label_9.setMinimumSize(QtCore.QSize(40, 40))
        self.label_9.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_9.setObjectName("label_9")
        self.label_backspace = QtWidgets.QLabel(parent=self.widget)
        self.label_backspace.setGeometry(QtCore.QRect(580, 10, 80, 40))
        self.label_backspace.setMinimumSize(QtCore.QSize(80, 40))
        self.label_backspace.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_backspace.setFont(font)
        self.label_backspace.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_backspace.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_backspace.setObjectName("label_backspace")
        self.label_Y = QtWidgets.QLabel(parent=self.widget)
        self.label_Y.setGeometry(QtCore.QRect(290, 55, 40, 40))
        self.label_Y.setMinimumSize(QtCore.QSize(40, 40))
        self.label_Y.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Y.setFont(font)
        self.label_Y.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_Y.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_Y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Y.setObjectName("label_Y")
        self.label_W = QtWidgets.QLabel(parent=self.widget)
        self.label_W.setGeometry(QtCore.QRect(110, 55, 40, 40))
        self.label_W.setMinimumSize(QtCore.QSize(40, 40))
        self.label_W.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_W.setFont(font)
        self.label_W.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_W.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_W.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_W.setObjectName("label_W")
        self.label_I = QtWidgets.QLabel(parent=self.widget)
        self.label_I.setGeometry(QtCore.QRect(380, 55, 40, 40))
        self.label_I.setMinimumSize(QtCore.QSize(40, 40))
        self.label_I.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_I.setFont(font)
        self.label_I.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_I.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_I.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_I.setObjectName("label_I")
        self.label_U = QtWidgets.QLabel(parent=self.widget)
        self.label_U.setGeometry(QtCore.QRect(335, 55, 40, 40))
        self.label_U.setMinimumSize(QtCore.QSize(40, 40))
        self.label_U.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_U.setFont(font)
        self.label_U.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_U.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_U.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_U.setObjectName("label_U")
        self.label_Q = QtWidgets.QLabel(parent=self.widget)
        self.label_Q.setGeometry(QtCore.QRect(65, 55, 40, 40))
        self.label_Q.setMinimumSize(QtCore.QSize(40, 40))
        self.label_Q.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Q.setFont(font)
        self.label_Q.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_Q.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_Q.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Q.setObjectName("label_Q")
        self.label_P = QtWidgets.QLabel(parent=self.widget)
        self.label_P.setGeometry(QtCore.QRect(470, 55, 40, 40))
        self.label_P.setMinimumSize(QtCore.QSize(40, 40))
        self.label_P.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_P.setFont(font)
        self.label_P.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_P.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_P.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_P.setObjectName("label_P")
        self.label_right_bracket = QtWidgets.QLabel(parent=self.widget)
        self.label_right_bracket.setGeometry(QtCore.QRect(560, 55, 40, 40))
        self.label_right_bracket.setMinimumSize(QtCore.QSize(40, 40))
        self.label_right_bracket.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_right_bracket.setFont(font)
        self.label_right_bracket.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_right_bracket.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_right_bracket.setObjectName("label_right_bracket")
        self.label_left_bracket = QtWidgets.QLabel(parent=self.widget)
        self.label_left_bracket.setGeometry(QtCore.QRect(515, 55, 40, 40))
        self.label_left_bracket.setMinimumSize(QtCore.QSize(40, 40))
        self.label_left_bracket.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_left_bracket.setFont(font)
        self.label_left_bracket.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_left_bracket.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_left_bracket.setObjectName("label_left_bracket")
        self.label_R = QtWidgets.QLabel(parent=self.widget)
        self.label_R.setGeometry(QtCore.QRect(200, 55, 40, 40))
        self.label_R.setMinimumSize(QtCore.QSize(40, 40))
        self.label_R.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_R.setFont(font)
        self.label_R.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_R.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_R.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_R.setObjectName("label_R")
        self.label_T = QtWidgets.QLabel(parent=self.widget)
        self.label_T.setGeometry(QtCore.QRect(245, 55, 40, 40))
        self.label_T.setMinimumSize(QtCore.QSize(40, 40))
        self.label_T.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_T.setFont(font)
        self.label_T.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_T.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_T.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_T.setObjectName("label_T")
        self.label_E = QtWidgets.QLabel(parent=self.widget)
        self.label_E.setGeometry(QtCore.QRect(155, 55, 40, 40))
        self.label_E.setMinimumSize(QtCore.QSize(40, 40))
        self.label_E.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_E.setFont(font)
        self.label_E.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_E.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_E.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_E.setObjectName("label_E")
        self.label_O = QtWidgets.QLabel(parent=self.widget)
        self.label_O.setGeometry(QtCore.QRect(425, 55, 40, 40))
        self.label_O.setMinimumSize(QtCore.QSize(40, 40))
        self.label_O.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_O.setFont(font)
        self.label_O.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_O.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_O.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_O.setObjectName("label_O")
        self.label_backslash = QtWidgets.QLabel(parent=self.widget)
        self.label_backslash.setGeometry(QtCore.QRect(605, 55, 55, 40))
        self.label_backslash.setMinimumSize(QtCore.QSize(55, 40))
        self.label_backslash.setMaximumSize(QtCore.QSize(55, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_backslash.setFont(font)
        self.label_backslash.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_backslash.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_backslash.setObjectName("label_backslash")
        self.label_K = QtWidgets.QLabel(parent=self.widget)
        self.label_K.setGeometry(QtCore.QRect(395, 100, 40, 40))
        self.label_K.setMinimumSize(QtCore.QSize(40, 40))
        self.label_K.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_K.setFont(font)
        self.label_K.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_K.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_K.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_K.setObjectName("label_K")
        self.label_F = QtWidgets.QLabel(parent=self.widget)
        self.label_F.setGeometry(QtCore.QRect(215, 100, 40, 40))
        self.label_F.setMinimumSize(QtCore.QSize(40, 40))
        self.label_F.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_F.setFont(font)
        self.label_F.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_F.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_F.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_F.setObjectName("label_F")
        self.label_L = QtWidgets.QLabel(parent=self.widget)
        self.label_L.setGeometry(QtCore.QRect(440, 100, 40, 40))
        self.label_L.setMinimumSize(QtCore.QSize(40, 40))
        self.label_L.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_L.setFont(font)
        self.label_L.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_L.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_L.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_L.setObjectName("label_L")
        self.label_H = QtWidgets.QLabel(parent=self.widget)
        self.label_H.setGeometry(QtCore.QRect(305, 100, 40, 40))
        self.label_H.setMinimumSize(QtCore.QSize(40, 40))
        self.label_H.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_H.setFont(font)
        self.label_H.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_H.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_H.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_H.setObjectName("label_H")
        self.label_S = QtWidgets.QLabel(parent=self.widget)
        self.label_S.setGeometry(QtCore.QRect(125, 100, 40, 40))
        self.label_S.setMinimumSize(QtCore.QSize(40, 40))
        self.label_S.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_S.setFont(font)
        self.label_S.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_S.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_S.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_S.setObjectName("label_S")
        self.label_A = QtWidgets.QLabel(parent=self.widget)
        self.label_A.setGeometry(QtCore.QRect(80, 100, 40, 40))
        self.label_A.setMinimumSize(QtCore.QSize(40, 40))
        self.label_A.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_A.setFont(font)
        self.label_A.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_A.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_A.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_A.setObjectName("label_A")
        self.label_D = QtWidgets.QLabel(parent=self.widget)
        self.label_D.setGeometry(QtCore.QRect(170, 100, 40, 40))
        self.label_D.setMinimumSize(QtCore.QSize(40, 40))
        self.label_D.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_D.setFont(font)
        self.label_D.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_D.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_D.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_D.setObjectName("label_D")
        self.label_G = QtWidgets.QLabel(parent=self.widget)
        self.label_G.setGeometry(QtCore.QRect(260, 100, 40, 40))
        self.label_G.setMinimumSize(QtCore.QSize(40, 40))
        self.label_G.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_G.setFont(font)
        self.label_G.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_G.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_G.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_G.setObjectName("label_G")
        self.label_semicolon = QtWidgets.QLabel(parent=self.widget)
        self.label_semicolon.setGeometry(QtCore.QRect(485, 100, 40, 40))
        self.label_semicolon.setMinimumSize(QtCore.QSize(40, 40))
        self.label_semicolon.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_semicolon.setFont(font)
        self.label_semicolon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_semicolon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_semicolon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_semicolon.setObjectName("label_semicolon")
        self.label_J = QtWidgets.QLabel(parent=self.widget)
        self.label_J.setGeometry(QtCore.QRect(350, 100, 40, 40))
        self.label_J.setMinimumSize(QtCore.QSize(40, 40))
        self.label_J.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_J.setFont(font)
        self.label_J.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_J.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_J.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_J.setObjectName("label_J")
        self.label_parantecy = QtWidgets.QLabel(parent=self.widget)
        self.label_parantecy.setGeometry(QtCore.QRect(530, 100, 40, 40))
        self.label_parantecy.setMinimumSize(QtCore.QSize(40, 40))
        self.label_parantecy.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_parantecy.setFont(font)
        self.label_parantecy.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_parantecy.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_parantecy.setObjectName("label_parantecy")
        self.label_enter = QtWidgets.QLabel(parent=self.widget)
        self.label_enter.setGeometry(QtCore.QRect(575, 100, 85, 40))
        self.label_enter.setMinimumSize(QtCore.QSize(85, 40))
        self.label_enter.setMaximumSize(QtCore.QSize(85, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_enter.setFont(font)
        self.label_enter.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_enter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_enter.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_enter.setObjectName("label_enter")
        self.label_C = QtWidgets.QLabel(parent=self.widget)
        self.label_C.setGeometry(QtCore.QRect(185, 145, 40, 40))
        self.label_C.setMinimumSize(QtCore.QSize(40, 40))
        self.label_C.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_C.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_C.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_C.setObjectName("label_C")
        self.label_B = QtWidgets.QLabel(parent=self.widget)
        self.label_B.setGeometry(QtCore.QRect(275, 145, 40, 40))
        self.label_B.setMinimumSize(QtCore.QSize(40, 40))
        self.label_B.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_B.setFont(font)
        self.label_B.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_B.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_B.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_B.setObjectName("label_B")
        self.label_forwardslash = QtWidgets.QLabel(parent=self.widget)
        self.label_forwardslash.setGeometry(QtCore.QRect(500, 145, 40, 40))
        self.label_forwardslash.setMinimumSize(QtCore.QSize(40, 40))
        self.label_forwardslash.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_forwardslash.setFont(font)
        self.label_forwardslash.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_forwardslash.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_forwardslash.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_forwardslash.setObjectName("label_forwardslash")
        self.label_colon = QtWidgets.QLabel(parent=self.widget)
        self.label_colon.setGeometry(QtCore.QRect(410, 145, 40, 40))
        self.label_colon.setMinimumSize(QtCore.QSize(40, 40))
        self.label_colon.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_colon.setFont(font)
        self.label_colon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_colon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_colon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_colon.setObjectName("label_colon")
        self.label_dot = QtWidgets.QLabel(parent=self.widget)
        self.label_dot.setGeometry(QtCore.QRect(455, 145, 40, 40))
        self.label_dot.setMinimumSize(QtCore.QSize(40, 40))
        self.label_dot.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_dot.setFont(font)
        self.label_dot.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_dot.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_dot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dot.setObjectName("label_dot")
        self.label_Z = QtWidgets.QLabel(parent=self.widget)
        self.label_Z.setGeometry(QtCore.QRect(95, 145, 40, 40))
        self.label_Z.setMinimumSize(QtCore.QSize(40, 40))
        self.label_Z.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Z.setFont(font)
        self.label_Z.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_Z.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_Z.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Z.setObjectName("label_Z")
        self.label_M = QtWidgets.QLabel(parent=self.widget)
        self.label_M.setGeometry(QtCore.QRect(365, 145, 40, 40))
        self.label_M.setMinimumSize(QtCore.QSize(40, 40))
        self.label_M.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_M.setFont(font)
        self.label_M.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_M.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_M.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_M.setObjectName("label_M")
        self.label_V = QtWidgets.QLabel(parent=self.widget)
        self.label_V.setGeometry(QtCore.QRect(230, 145, 40, 40))
        self.label_V.setMinimumSize(QtCore.QSize(40, 40))
        self.label_V.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_V.setFont(font)
        self.label_V.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_V.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_V.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_V.setObjectName("label_V")
        self.label_N = QtWidgets.QLabel(parent=self.widget)
        self.label_N.setGeometry(QtCore.QRect(320, 145, 40, 40))
        self.label_N.setMinimumSize(QtCore.QSize(40, 40))
        self.label_N.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_N.setFont(font)
        self.label_N.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_N.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_N.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_N.setObjectName("label_N")
        self.label_X = QtWidgets.QLabel(parent=self.widget)
        self.label_X.setGeometry(QtCore.QRect(140, 145, 40, 40))
        self.label_X.setMinimumSize(QtCore.QSize(40, 40))
        self.label_X.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_X.setFont(font)
        self.label_X.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_X.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_X.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_X.setObjectName("label_X")
        self.label_right_shift = QtWidgets.QLabel(parent=self.widget)
        self.label_right_shift.setGeometry(QtCore.QRect(545, 145, 115, 40))
        self.label_right_shift.setMinimumSize(QtCore.QSize(115, 40))
        self.label_right_shift.setMaximumSize(QtCore.QSize(115, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_right_shift.setFont(font)
        self.label_right_shift.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_right_shift.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_right_shift.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_right_shift.setObjectName("label_right_shift")
        self.label_left_ctrl = QtWidgets.QLabel(parent=self.widget)
        self.label_left_ctrl.setGeometry(QtCore.QRect(10, 190, 65, 40))
        self.label_left_ctrl.setMinimumSize(QtCore.QSize(65, 40))
        self.label_left_ctrl.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_left_ctrl.setFont(font)
        self.label_left_ctrl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_left_ctrl.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_left_ctrl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_left_ctrl.setObjectName("label_left_ctrl")
        self.label_left_alt = QtWidgets.QLabel(parent=self.widget)
        self.label_left_alt.setGeometry(QtCore.QRect(80, 190, 80, 40))
        self.label_left_alt.setMinimumSize(QtCore.QSize(80, 40))
        self.label_left_alt.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_left_alt.setFont(font)
        self.label_left_alt.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_left_alt.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_left_alt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_left_alt.setObjectName("label_left_alt")
        self.label_right = QtWidgets.QLabel(parent=self.widget)
        self.label_right.setGeometry(QtCore.QRect(625, 190, 35, 40))
        self.label_right.setMinimumSize(QtCore.QSize(35, 40))
        self.label_right.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_right.setFont(font)
        self.label_right.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_right.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_right.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_right.setObjectName("label_right")
        self.label_up = QtWidgets.QLabel(parent=self.widget)
        self.label_up.setGeometry(QtCore.QRect(570, 190, 50, 18))
        self.label_up.setMinimumSize(QtCore.QSize(50, 18))
        self.label_up.setMaximumSize(QtCore.QSize(35, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_up.setFont(font)
        self.label_up.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_up.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_up.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_up.setObjectName("label_up")
        self.label_down = QtWidgets.QLabel(parent=self.widget)
        self.label_down.setGeometry(QtCore.QRect(570, 211, 50, 18))
        self.label_down.setMinimumSize(QtCore.QSize(50, 18))
        self.label_down.setMaximumSize(QtCore.QSize(35, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_down.setFont(font)
        self.label_down.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_down.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_down.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_down.setObjectName("label_down")
        self.label_left = QtWidgets.QLabel(parent=self.widget)
        self.label_left.setGeometry(QtCore.QRect(530, 190, 35, 40))
        self.label_left.setMinimumSize(QtCore.QSize(35, 40))
        self.label_left.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_left.setFont(font)
        self.label_left.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_left.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_left.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_left.setObjectName("label_left")
        self.label_right_ctrl = QtWidgets.QLabel(parent=self.widget)
        self.label_right_ctrl.setGeometry(QtCore.QRect(490, 190, 35, 40))
        self.label_right_ctrl.setMinimumSize(QtCore.QSize(35, 40))
        self.label_right_ctrl.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_right_ctrl.setFont(font)
        self.label_right_ctrl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_right_ctrl.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_right_ctrl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_right_ctrl.setObjectName("label_right_ctrl")
        self.label_right_alt = QtWidgets.QLabel(parent=self.widget)
        self.label_right_alt.setGeometry(QtCore.QRect(450, 190, 35, 40))
        self.label_right_alt.setMinimumSize(QtCore.QSize(35, 40))
        self.label_right_alt.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_right_alt.setFont(font)
        self.label_right_alt.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_right_alt.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_right_alt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_right_alt.setObjectName("label_right_alt")
        self.label_space = QtWidgets.QLabel(parent=self.widget)
        self.label_space.setGeometry(QtCore.QRect(165, 190, 280, 40))
        self.label_space.setMinimumSize(QtCore.QSize(280, 40))
        self.label_space.setMaximumSize(QtCore.QSize(35, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_space.setFont(font)
        self.label_space.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0); border-radius: 5px; border: 1px solid grey;")
        self.label_space.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_space.setText("")
        self.label_space.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_space.setObjectName("label_space")

        QtCore.QMetaObject.connectSlotsByName(self)
        if self.lang == 'en':
            self.en_keyboard()
        elif self.lang == 'ru':
            self.ru_keyboard()


    def ru_keyboard(self):
        self.label_yo.setText("Ё")
        self.label_tab.setText("Tab")
        self.label_caps.setText("Caps Lock")
        self.label_left_shift.setText("Shift")
        self.label_1.setText("1 !")
        self.label_2.setText("2 \"")
        self.label_3.setText("3№")
        self.label_4.setText("4  ;")
        self.label_5.setText("5 %")
        self.label_6.setText("6 :")
        self.label_7.setText("7 ?")
        self.label_8.setText("8 *")
        self.label_9.setText(" 9 (")
        self.label_0.setText(" 0 )")
        self.label_equal.setText("= +")
        self.label_minus.setText("- _")
        self.label_backspace.setText("Backspace")
        self.label_Y.setText("Н")
        self.label_W.setText("Ц")
        self.label_I.setText("Ш")
        self.label_U.setText("Г")
        self.label_Q.setText("Й")
        self.label_P.setText("З")
        self.label_right_bracket.setText("  Х")
        self.label_left_bracket.setText("  Ъ")
        self.label_R.setText("К")
        self.label_T.setText("Е")
        self.label_E.setText("У")
        self.label_O.setText("Щ")
        self.label_backslash.setText("  \\ /")
        self.label_K.setText("Л")
        self.label_F.setText("А")
        self.label_L.setText("Д")
        self.label_H.setText("Р")
        self.label_S.setText("Ы")
        self.label_A.setText("Ф")
        self.label_D.setText("В")
        self.label_G.setText("П")
        self.label_semicolon.setText(" Ж")
        self.label_J.setText("О")
        self.label_parantecy.setText("  Э")
        self.label_enter.setText("Enter")
        self.label_C.setText("С")
        self.label_B.setText("И")
        self.label_forwardslash.setText(". ,")
        self.label_colon.setText("Б")
        self.label_dot.setText("Ю")
        self.label_Z.setText("Я")
        self.label_M.setText("Ь")
        self.label_V.setText("М")
        self.label_N.setText("Т")
        self.label_X.setText("Ч")
        self.label_right_shift.setText("Shift")
        self.label_left_ctrl.setText("Ctrl")
        self.label_left_alt.setText("Alt")
        self.label_right.setText(">")
        self.label_up.setText("^")
        self.label_down.setText("v")
        self.label_left.setText("<")
        self.label_right_ctrl.setText("Ctrl")
        self.label_right_alt.setText("Alt")

    def en_keyboard(self):
        self.label_yo.setText("`~")
        self.label_tab.setText("Tab")
        self.label_caps.setText("Caps Lock")
        self.label_left_shift.setText("Shift")
        self.label_1.setText("1 !")
        self.label_2.setText("2 @")
        self.label_4.setText("4 $")
        self.label_3.setText("3 #")
        self.label_6.setText("6 ^")
        self.label_5.setText("5 %")
        self.label_8.setText("8 *")
        self.label_7.setText("7 &")
        self.label_0.setText("0 )")
        self.label_equal.setText("= +")
        self.label_minus.setText("- _")
        self.label_9.setText("9 (")
        self.label_backspace.setText("Backspace")
        self.label_Y.setText("Y")
        self.label_W.setText("W")
        self.label_I.setText("I")
        self.label_U.setText("U")
        self.label_Q.setText("Q")
        self.label_P.setText("P")
        self.label_right_bracket.setText("]  }")
        self.label_left_bracket.setText("[  {")
        self.label_R.setText("R")
        self.label_T.setText("T")
        self.label_E.setText("E")
        self.label_O.setText("O")
        self.label_backslash.setText("  |  \\")
        self.label_K.setText("K")
        self.label_F.setText("F")
        self.label_L.setText("L")
        self.label_H.setText("H")
        self.label_S.setText("S")
        self.label_A.setText("A")
        self.label_D.setText("D")
        self.label_G.setText("G")
        self.label_semicolon.setText(";  :")
        self.label_J.setText("J")
        self.label_parantecy.setText("\'  \"")
        self.label_enter.setText("Enter")
        self.label_C.setText("C")
        self.label_B.setText("B")
        self.label_forwardslash.setText("/  ?")
        self.label_colon.setText(",  <")
        self.label_dot.setText(".  >")
        self.label_Z.setText("Z")
        self.label_M.setText("M")
        self.label_V.setText("V")
        self.label_N.setText("N")
        self.label_X.setText("X")
        self.label_right_shift.setText("Shift")
        self.label_left_ctrl.setText("Ctrl")
        self.label_left_alt.setText("Alt")
        self.label_right.setText(">")
        self.label_up.setText("^")
        self.label_down.setText("v")
        self.label_left.setText("<")
        self.label_right_ctrl.setText("Ctrl")
        self.label_right_alt.setText("Alt")


    def change_keyboard(self, lang):
        self.lang = lang
